### ISSUE TITLE
 trac-code-comments-plugin doesn't work in Trac 1.4.1

### ISSUE THREAD

**Issue by iqbal1979** [trac-hacks/trac-code-comments-plugin#78]
This plugin doesn't work in latest Trac 1.4.1

```
2020-03-09 10:16:56,094 Trac[web_ui] INFO: Installing plugin TracCodeComments-1.1.0-py2.7.egg
2020-03-09 10:16:56,095 Trac[web_ui] INFO: Plugin TracCodeComments-1.1.0-py2.7.egg installed to /home/TRAC/plugins/TracCodeComments-1.1.0-py2.7.egg
2020-03-09 10:16:56,337 Trac[env] INFO: Reloading environment due to configuration change
2020-03-09 10:16:56,364 Trac[env] INFO: -------------------------------- environment startup [Trac 1.4.1] --------------------------------
2020-03-09 10:16:56,467 Trac[loader] ERROR: Skipping "ckintegration = ckintegration": ImportError: cannot import name Context
2020-03-09 10:16:56,470 Trac[loader] ERROR: Skipping "code_comments = code_comments": ImportError: cannot import name Context
2020-03-09 10:16:56,758 Trac[chrome] WARNING: Component TotalHoursFilter relies on deprecated Genshi stream filtering
```
